photocutter added
Y2Kot/Visitor-bot pull request #5
Opened 2023-04-03 08:50 UTC by Kurush7

2023-04-07 11:55 UTC, Y2Kot requested changes

2023-04-07 11:55 UTC, Y2Kot commented on photocutter/build.gradle.kts
> +    sourceCompatibility = JavaVersion.VERSION_1_8
замени везде на JavaVersion.VERSION_11

2023-04-07 11:55 UTC, Y2Kot commented on photocutter/build.gradle.kts
> +repositories {
подлил изменения, больше в каждом модуле не нужно указывать репозитории для зависимостей

2023-04-07 11:55 UTC, Y2Kot commented on photocutter/desktop/build.gradle.kts
> +    implementation("org.bytedeco:javacv-platform:1.5.8")
добавь как зависимости в toml (папка gradle)

2023-04-07 11:55 UTC, Y2Kot commented on photocutter/src/main/java/com/example/photocutter/Utils.kt
> +        val newOrder = emptyList<Int>().toMutableList()
val list = mutableListOf<Int>()

2023-04-07 11:55 UTC, Y2Kot commented on photocutter/src/main/java/com/example/photocutter/PriorBox.kt
> +        priors = generatePriors()
тут нужен блок инициализации?

2023-04-13 19:20 UTC, Y2Kot commented on photocutter/src/main/java/com/example/photocutter/PriorBox.kt
> +        priors = generatePriors()
Почему не:
`private val priors: Array<FloatArray> = generatePriors()`

2023-04-13 19:22 UTC, Y2Kot commented on photocutter/build.gradle.kts
> +    sourceCompatibility = JavaVersion.VERSION_1_11
JavaVersion.VERSION_11
разве не так?

2023-04-13 19:24 UTC, Kurush7 commented on photocutter/src/main/java/com/example/photocutter/PriorBox.kt
> +        priors = generatePriors()
внутри зависимость от imgw и imgh из конструктора

2023-04-13 20:33 UTC, Y2Kot approved these changes

2023-04-13 20:33 UTC, merged